owner: cowprotocol
repo: uptime-periphery

notifications:
  - type: slack
    webhook-url: $SLACK_WEBHOOK_URL

sites:
  - name: TEST - Intentional Failure (Remove After Testing)
    url: https://this-url-does-not-exist-12345678.com
    maxResponseTime: 5000
    notifications:
      - type: telegram
        chat-id: $TELEGRAM_CHAT_ID_NEAR
        bot-token: $TELEGRAM_BOT_TOKEN

  - name: Bridging - Near/1Click/Tokens
    url: https://1click.chaindefuser.com/v0/tokens
    notifications:
      - type: telegram
        chat-id: $TELEGRAM_CHAT_ID_NEAR
        bot-token: $TELEGRAM_BOT_TOKEN

  - name: Bridging - Near/1Click/Quote
    method: POST
    url: https://1click.chaindefuser.com/v0/quote
    headers: ["Content-Type: application/json"]
    notifications:
      - type: telegram
        chat-id: $TELEGRAM_CHAT_ID_NEAR
        bot-token: $TELEGRAM_BOT_TOKEN
    body: |
      {
        "dry": false,
        "swapType": "EXACT_INPUT",
        "slippageTolerance": 100,
        "originAsset": "nep141:arb-0xaf88d065e77c8cc2239327c5edb3a432268e5831.omft.near",
        "depositType": "ORIGIN_CHAIN",
        "destinationAsset": "nep141:base-0x833589fcd6edb6e08f4c7c32d4f71b54bda02913.omft.near",
        "amount": "3241870412",
        "refundTo": "0x79063d9173C09887d536924E2F6eADbaBAc099f5",
        "refundType": "ORIGIN_CHAIN",
        "recipient": "0x79063d9173C09887d536924E2F6eADbaBAc099f5",
        "recipientType": "DESTINATION_CHAIN",
        "deadline": "2030-01-01T00:00:00Z"
      }

status-website:
  cname: periphery.status.cow.fi
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/uptime-periphery/master/assets/cow-logo.png
  name: Upptime for periphery services
  introTitle: "**Upptime** for periphery services of CoW Protocol"
  introMessage: This is a status page for periphery services of CoW Protocol.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
