owner: cowprotocol
repo: uptime-periphery

assignees:
  - cowprotocol/frontend

notifications:
  - type: slack
    webhook-url: $SLACK_WEBHOOK_URL

sites:
  - name: Bridging - Near's 1Click - Get tokens
    url: https://1click.chaindefuser.com/v0/tokens
    icon: https://www.near.org/favicon.ico

  - name: Bridging - Near's 1Click - Get Quote
    method: POST
    url: https://1click.chaindefuser.com/v0/quote
    icon: https://www.near.org/favicon.ico
    headers: ["Content-Type: application/json"]

    body: |
      {
        "dry": false,
        "swapType": "EXACT_INPUT",
        "slippageTolerance": 100,
        "originAsset": "nep141:arb-0xaf88d065e77c8cc2239327c5edb3a432268e5831.omft.near",
        "depositType": "ORIGIN_CHAIN",
        "destinationAsset": "nep141:base-0x833589fcd6edb6e08f4c7c32d4f71b54bda02913.omft.near",
        "amount": "3241870412",
        "refundTo": "0x79063d9173C09887d536924E2F6eADbaBAc099f5",
        "refundType": "ORIGIN_CHAIN",
        "recipient": "0x79063d9173C09887d536924E2F6eADbaBAc099f5",
        "recipientType": "DESTINATION_CHAIN",
        "deadline": "2030-01-01T00:00:00Z"
      }

  - name: Bridging - Bungee - Get tokens
    url: https://backend.bungee.exchange/api/v1/bungee-manual/dest-tokens?toChainId=42161&includeBridges=across%2Ccctp%2Cgnosis-native-bridge&fromChainId=1
    icon: https://img.notionusercontent.com/s3/prod-files-secure%2F3ff6c9ca-a668-43fc-b125-7cac785409a3%2Fbefa5cd6-8537-43ee-868a-796111e9bfcb%2Fnew_(10).png/size/w=250?exp=1762607758&sig=nkhKAvPK1rpH7I4BZ5et6sSbNYSr4ZYm67KaZhK98S4&id=185818fd-2858-80d8-8fcc-d82b3b4adbf4&table=block
    headers:
      - "Referer: https://swap.cow.fi/"

  - name: Bridging - Bungee - Get Quote
    url: https://backend.bungee.exchange/api/v1/bungee/quote?userAddress=0xAcaf8cC69BF6BadbEc19c55BC87D2E60Dbc24e2F&originChainId=1&destinationChainId=42161&inputToken=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&inputAmount=3175278561&receiverAddress=0x79063d9173C09887d536924E2F6eADbaBAc099f5&outputToken=0xaf88d065e77c8cC2239327C5EDb3A432268e5831&includeBridges=across%2Ccctp%2Cgnosis-native-bridge&enableManual=true&disableSwapping=true&disableAuto=true
    icon: https://img.notionusercontent.com/s3/prod-files-secure%2F3ff6c9ca-a668-43fc-b125-7cac785409a3%2Fbefa5cd6-8537-43ee-868a-796111e9bfcb%2Fnew_(10).png/size/w=250?exp=1762607758&sig=nkhKAvPK1rpH7I4BZ5et6sSbNYSr4ZYm67KaZhK98S4&id=185818fd-2858-80d8-8fcc-d82b3b4adbf4&table=block
    headers:
      - "Referer: https://swap.cow.fi/"
      - "affiliate": "609913096e1a3d62cecd0ffff47aa3e459eaedceb5fef75aad43e6cbff367039708902197e0b2b78b1d76cb0837ad0b318baedceb5fef75aad43e6cb"

status-website:
  cname: periphery.status.cow.fi
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/uptime-periphery/master/assets/cow-logo.png
  name: Upptime for periphery services
  introTitle: "**Upptime** for periphery services of CoW Protocol"
  introMessage: This is a status page for periphery services of CoW Protocol.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
